// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrkjsazhofdrszbjzgdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZya2pzYXpob2ZkcnN6Ymp6Z2RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY1MDEzNzgsImV4cCI6MjA4MjA3NzM3OH0.Fko-zfpKLvp9-tWjTT_z6_41cH4BWiU3IJNQIxnihqc";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});